IS_DEBUG = True
RETRIES_MAX =5
RETRY_DELAY_IN_SEC = 5
SATANG_NAME = 'SATANG'
BINANCE_NAME = 'BINANCE'
BITKUB_NAME = 'BITKUB'
SATANG_TRADING_FEE_PERCENTAGE = 0.2
BINANCE_TRADING_FEE_PERCENTAGE = 0.1
BITKUB_TRADING_FEE_PERCENTAGE = 0.25

TYPE_BUY = 'BUY'
TYPE_SELL = 'SELL'
TYPE_SCAN = 'SCAN'
TYPE_TRANSFER = 'TRANSFER'

XLM_COIN='XLM'
XRP_COIN='XRP'
ADA_COIN='ADA'
USDT_COIN='USDT'
BNB_COIN='BNB'
DAI_COIN='DAI'
LTC_COIN='LTC'
BAND_COIN='BAND'
BAT_COIN='BAT'
BCH_COIN='BCH'
BTC_COIN='BTC'
DOGE_COIN='DOGE'
DOT_COIN='DOT'
ETH_COIN='ETH'
JFIN_COIN='JFIN'
LINK_COIN='LINK'
USDC_COIN='USDC'
TRANSFER_FEE_FIELD='transfer_fee'
MAX_BUY_QUANTITY_FIELD='max_buy_quantity_field'
MIN_BUY_QUANTITY_FIELD='min_buy_quantity_field'

'''
ISSUE: fees are refreshed 3 times a day
https://www.bitkub.com/fee/cryptocurrency
'''
SYMBOL_CONFIGS ={
    XLM_COIN: { TRANSFER_FEE_FIELD: 0.02, MAX_BUY_QUANTITY_FIELD: 1000, MIN_BUY_QUANTITY_FIELD: 500}, # checked
    XRP_COIN: { TRANSFER_FEE_FIELD: 0.25, MAX_BUY_QUANTITY_FIELD: 100, MIN_BUY_QUANTITY_FIELD: 30}, # checked
    ADA_COIN: { TRANSFER_FEE_FIELD: 1, MAX_BUY_QUANTITY_FIELD: 50, MIN_BUY_QUANTITY_FIELD: 10},  # checked
    USDT_COIN: { TRANSFER_FEE_FIELD:  1, MAX_BUY_QUANTITY_FIELD: 200, MIN_BUY_QUANTITY_FIELD: 100},  # checked
    BNB_COIN: { TRANSFER_FEE_FIELD: 0.0005, MAX_BUY_QUANTITY_FIELD: 2, MIN_BUY_QUANTITY_FIELD: 0.02},  # checked0.001
    DAI_COIN: { TRANSFER_FEE_FIELD: 15, MAX_BUY_QUANTITY_FIELD: 100, MIN_BUY_QUANTITY_FIELD: 100}, # checked
    LTC_COIN: { TRANSFER_FEE_FIELD: 0.001, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1}, # checked
    BAND_COIN: { TRANSFER_FEE_FIELD: 0.01, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1}, # checked
    BAT_COIN: { TRANSFER_FEE_FIELD: 26, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1}, # checked
    BCH_COIN: { TRANSFER_FEE_FIELD: 0.001, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1},  # checked
    BTC_COIN: { TRANSFER_FEE_FIELD: 0.00057, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1},# checked
    DOGE_COIN: { TRANSFER_FEE_FIELD: 5, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1},# checked
    DOT_COIN: { TRANSFER_FEE_FIELD: 0.1, MAX_BUY_QUANTITY_FIELD: 5, MIN_BUY_QUANTITY_FIELD: 3},# checked
    ETH_COIN: { TRANSFER_FEE_FIELD: 0.01, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1},# checked
    JFIN_COIN: { TRANSFER_FEE_FIELD: 90.5, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1},# checked
    LINK_COIN: { TRANSFER_FEE_FIELD: 0.81, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1},# checked
    USDC_COIN: { TRANSFER_FEE_FIELD: 10, MAX_BUY_QUANTITY_FIELD: 10000, MIN_BUY_QUANTITY_FIELD: 1}# checked
}

# XLM: Fast, cheapest transfer fee but low volume on SatangPro (300k THB)
# XRP: Slow speed (could take up to 3 mins), average volume on SatangPro (1.6M THB)
# ADA: transfers quite quickly. It usually confirms in about 20 seconds. High volume: 6M THB volume average per day on SatangPro
# BNB: High volume: 3M THB volume average per day on SatangPro. Binance withdrawal fee: 0.2 bnb
#   Binance Coin (BNB) normally takes not more than 3-4 hours for confirmations to meet the required amount of destination address
